version: "3"

services:
  postgres:
    container_name: noosfero-database
    image: postgres:9.4
    environment:
      POSTGRES_USER: noosfero
      POSTGRES_PASSWORD: noosfero
    volumes:
      - pg-data:/var/lib/postgresql/data

  noosfero:
    container_name: noosfero
    build:
      context: .
      dockerfile: ./config/docker/dev/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/noosfero
    environment:
      POSTGRES_USER: noosfero
      POSTGRES_PASSWORD: noosfero

volumes:
  pg-data: {}
